-- Merchant onboarding full flow: extended statuses, risk, integrations, stores, settlement, audit

-- Extend onboarding_status enum (PostgreSQL)
ALTER TYPE onboarding_status ADD VALUE IF NOT EXISTS 'PENDING_KYC_DOCUMENTS';
ALTER TYPE onboarding_status ADD VALUE IF NOT EXISTS 'PENDING_KYC_APPROVAL';
ALTER TYPE onboarding_status ADD VALUE IF NOT EXISTS 'KYC_REJECTED';
ALTER TYPE onboarding_status ADD VALUE IF NOT EXISTS 'PENDING_RISK_REVIEW';
ALTER TYPE onboarding_status ADD VALUE IF NOT EXISTS 'RISK_REJECTED';
ALTER TYPE onboarding_status ADD VALUE IF NOT EXISTS 'PENDING_BANK_VALIDATION';
ALTER TYPE onboarding_status ADD VALUE IF NOT EXISTS 'BANK_VALIDATION_FAILED';
ALTER TYPE onboarding_status ADD VALUE IF NOT EXISTS 'BANK_VALIDATED';
ALTER TYPE onboarding_status ADD VALUE IF NOT EXISTS 'PENDING_TPS_REGISTRATION';
ALTER TYPE onboarding_status ADD VALUE IF NOT EXISTS 'TPS_REGISTRATION_FAILED';
ALTER TYPE onboarding_status ADD VALUE IF NOT EXISTS 'TPS_REGISTERED';
ALTER TYPE onboarding_status ADD VALUE IF NOT EXISTS 'PENDING_ALIAS_QR_SETUP';
ALTER TYPE onboarding_status ADD VALUE IF NOT EXISTS 'ALIAS_QR_FAILED';
ALTER TYPE onboarding_status ADD VALUE IF NOT EXISTS 'ALIAS_QR_REGISTERED';
ALTER TYPE onboarding_status ADD VALUE IF NOT EXISTS 'PENDING_SETTLEMENT_SETUP';
ALTER TYPE onboarding_status ADD VALUE IF NOT EXISTS 'SETTLEMENT_APPROVAL_PENDING';
ALTER TYPE onboarding_status ADD VALUE IF NOT EXISTS 'SETTLEMENT_REJECTED';
ALTER TYPE onboarding_status ADD VALUE IF NOT EXISTS 'SETTLEMENT_APPROVED';
ALTER TYPE onboarding_status ADD VALUE IF NOT EXISTS 'READY_FOR_ACTIVATION';
ALTER TYPE onboarding_status ADD VALUE IF NOT EXISTS 'ACTIVE';
ALTER TYPE onboarding_status ADD VALUE IF NOT EXISTS 'SUSPENDED';
ALTER TYPE onboarding_status ADD VALUE IF NOT EXISTS 'FAILED';
