export const ONBOARDING_STEPS = {
  ENTITY_PROFILE: 'ENTITY_PROFILE',
  KYC_DOCUMENTS: 'KYC_DOCUMENTS',
  BENEFICIAL_OWNERS: 'BENEFICIAL_OWNERS',
  SETTLEMENT_ACCOUNT: 'SETTLEMENT_ACCOUNT',
  AML_SCREENING: 'AML_SCREENING',
} as const;

export type OnboardingStepCode =
  (typeof ONBOARDING_STEPS)[keyof typeof ONBOARDING_STEPS];

export const DEFAULT_MERCHANT_STEPS: OnboardingStepCode[] = [
  ONBOARDING_STEPS.ENTITY_PROFILE,
  ONBOARDING_STEPS.KYC_DOCUMENTS,
  ONBOARDING_STEPS.BENEFICIAL_OWNERS,
  ONBOARDING_STEPS.SETTLEMENT_ACCOUNT,
  ONBOARDING_STEPS.AML_SCREENING,
];
