export const ONBOARDING_STEPS = {
  ENTITY_PROFILE: 'ENTITY_PROFILE',
  KYC_DOCUMENTS: 'KYC_DOCUMENTS',
  BENEFICIAL_OWNERS: 'BENEFICIAL_OWNERS',
  SETTLEMENT_ACCOUNT: 'SETTLEMENT_ACCOUNT',
  AML_SCREENING: 'AML_SCREENING',
  RISK_REVIEW: 'RISK_REVIEW',
  BANK_VALIDATION: 'BANK_VALIDATION',
  TPS_REGISTRATION: 'TPS_REGISTRATION',
  ALIAS_QR_SETUP: 'ALIAS_QR_SETUP',
  SETTLEMENT_CONFIG: 'SETTLEMENT_CONFIG',
  FINAL_REVIEW: 'FINAL_REVIEW',
} as const;

export type OnboardingStepCode =
  (typeof ONBOARDING_STEPS)[keyof typeof ONBOARDING_STEPS];

export const DEFAULT_MERCHANT_STEPS: OnboardingStepCode[] = [
  ONBOARDING_STEPS.ENTITY_PROFILE,
  ONBOARDING_STEPS.KYC_DOCUMENTS,
  ONBOARDING_STEPS.BENEFICIAL_OWNERS,
  ONBOARDING_STEPS.SETTLEMENT_ACCOUNT,
  ONBOARDING_STEPS.AML_SCREENING,
  ONBOARDING_STEPS.RISK_REVIEW,
  ONBOARDING_STEPS.BANK_VALIDATION,
  ONBOARDING_STEPS.TPS_REGISTRATION,
  ONBOARDING_STEPS.ALIAS_QR_SETUP,
  ONBOARDING_STEPS.SETTLEMENT_CONFIG,
  ONBOARDING_STEPS.FINAL_REVIEW,
];

export const WIZARD_STEP_ORDER: OnboardingStepCode[] = [
  ONBOARDING_STEPS.ENTITY_PROFILE,
  ONBOARDING_STEPS.KYC_DOCUMENTS,
  ONBOARDING_STEPS.SETTLEMENT_ACCOUNT,
  ONBOARDING_STEPS.RISK_REVIEW,
  ONBOARDING_STEPS.TPS_REGISTRATION,
  ONBOARDING_STEPS.ALIAS_QR_SETUP,
  ONBOARDING_STEPS.SETTLEMENT_CONFIG,
  ONBOARDING_STEPS.FINAL_REVIEW,
];
