import * as Joi from 'joi';

export const envValidationSchema = Joi.object({
  NODE_ENV: Joi.string()
    .valid('development', 'production', 'test')
    .default('development'),
  PORT: Joi.number().default(3001),
  DATABASE_URL: Joi.string().required(),
  DIRECT_DATABASE_URL: Joi.string().required(),
  SUPABASE_URL: Joi.string().uri().optional(),
  SUPABASE_SERVICE_ROLE_KEY: Joi.string().optional(),
  REDIS_URL: Joi.string().optional(),
  REDIS_ENABLED: Joi.string().valid('true', 'false').optional(),
  RABBITMQ_URL: Joi.string().optional(),
  RABBITMQ_ENABLED: Joi.string().valid('true', 'false').optional(),
  RABBITMQ_EXCHANGE: Joi.string().optional(),
  CORS_ORIGIN: Joi.string().optional(),
  JWT_ACCESS_SECRET: Joi.string().optional(),
  JWT_REFRESH_SECRET: Joi.string().optional(),
  JWT_ACCESS_EXPIRES_IN: Joi.string().optional(),
  JWT_REFRESH_EXPIRES_IN: Joi.string().optional(),
  SWAGGER_ENABLED: Joi.string().valid('true', 'false').optional(),
  SWAGGER_TITLE: Joi.string().optional(),
  SWAGGER_DESCRIPTION: Joi.string().optional(),
  SWAGGER_VERSION: Joi.string().optional(),
  AUDIT_ENABLED: Joi.string().valid('true', 'false').optional(),
  MAIL_ENABLED: Joi.string().valid('true', 'false').optional(),
  MAIL_HOST: Joi.string().optional(),
  MAIL_PORT: Joi.number().optional(),
  MAIL_SECURE: Joi.string().valid('true', 'false').optional(),
  MAIL_USER: Joi.string().allow('').optional(),
  MAIL_PASS: Joi.string().allow('').optional(),
  MAIL_FROM: Joi.string().allow('').optional(),
  AUTH_MAX_FAILED_ATTEMPTS: Joi.number().optional(),
  AUTH_LOCKOUT_MINUTES: Joi.number().optional(),
  AUTH_REFRESH_COOKIE_NAME: Joi.string().optional(),
  AUTH_PASSWORD_RESET_HOURS: Joi.number().optional(),
  MFA_ENCRYPTION_KEY: Joi.string().length(64).optional(),
  MFA_ISSUER: Joi.string().optional(),
  BCRYPT_ROUNDS: Joi.number().optional(),
  THROTTLE_TTL_MS: Joi.number().optional(),
  THROTTLE_LIMIT: Joi.number().optional(),
  THROTTLE_AUTH_LIMIT: Joi.number().optional(),
  ARGON2_MEMORY_COST_KIB: Joi.number().optional(),
  ARGON2_TIME_COST: Joi.number().optional(),
  ARGON2_PARALLELISM: Joi.number().optional(),
  AUTH_PRIVILEGED_ROLE_CODES: Joi.string().optional(),
  ARGON2_MIGRATION_START_DATE: Joi.string().optional(),
  ARGON2_BACKSTOP_DAYS: Joi.number().optional(),
  ARGON2_BACKSTOP_WARNING_DAYS: Joi.number().optional(),
  JWT_PUBLIC_KEY_CACHE_TTL_MS: Joi.number().optional(),
  VAULT_ADDR: Joi.string().optional(),
  VAULT_TOKEN: Joi.string().optional(),
  VAULT_ROLE_ID: Joi.string().optional(),
  VAULT_SECRET_ID: Joi.string().optional(),
  VAULT_JWT_KEY_NAME: Joi.string().optional(),
  VAULT_QR_KEY_NAME: Joi.string().optional(),
  TIPS_WEBHOOK_SECRET: Joi.string().optional(),
  PAYMENT_TIMEOUT_MINUTES: Joi.number().optional(),
  SETTLEMENT_DEFAULT_MDR_RATE: Joi.number().optional(),
});
